const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('node:fs'), assert=require('node:assert/strict'), {spawn}=require('node:child_process');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const localPython=path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const python=process.env.EUREKA_PYTHON || (fs.existsSync(localPython)?localPython:'python');
const child=spawn(python,[path.join(__dirname,'ui_bridge.py')],{cwd:root,env:{...process.env,PYTHONPATH:root},stdio:['pipe','pipe','pipe']});
let next=0, buffer='';const waiting=new Map();
child.stdout.on('data',chunk=>{buffer+=chunk;for(let end;(end=buffer.indexOf('\n'))>=0;){const row=JSON.parse(buffer.slice(0,end));buffer=buffer.slice(end+1);waiting.get(row.id)(new Response(row.status===204?null:row.body,{status:row.status,headers:{'Content-Type':'application/json'}}));waiting.delete(row.id);}});
const errors=[]; const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(root+'/app/static/index.html','utf8'),{url:'http://localhost/',runScripts:'outside-only',virtualConsole:vc});
const w=dom.window,d=w.document;
w.fetch=(path,options={})=>new Promise(resolve=>{const id=++next; waiting.set(id,resolve);child.stdin.write(JSON.stringify({id,path,method:options.method||'GET',body:options.body?JSON.parse(options.body):undefined})+'\n');});
w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
w.eval(fs.readFileSync(root+'/app/static/app.js','utf8'));
const wait=async(fn)=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,25));}throw Error('DOM condition timed out: '+fn.toString()+' feedback='+d.querySelector('#feedback').textContent)};
const click=s=>d.querySelector(s).click();
(async()=>{
 await wait(()=>d.querySelector('#try-demo'));click('#try-demo');await wait(()=>d.querySelectorAll('.card').length===6);
 assert.equal(d.querySelector('#demo-banner').hidden,false);
 click('.save-btn');await wait(()=>d.querySelector('#saved-count').textContent==='1');
 click('[data-view="saved"]');await wait(()=>d.querySelectorAll('.card').length===1);
 click('.card-title button');await wait(()=>d.querySelector('dialog[open]'));
 d.querySelector('#bookmark-note').value='Useful for my report';click('#save-note');await wait(()=>d.querySelector('#toast').textContent==='Record and note saved');
 click('#close-details');click('.card-title button');await wait(()=>d.querySelector('dialog[open]'));
 assert.equal(d.querySelector('#bookmark-note').value,'Useful for my report');click('#close-details');
 click('[data-view="conference"]');await wait(()=>d.querySelectorAll('.card').length===5);
 d.querySelector('#deadline').value='open';d.querySelector('#deadline').dispatchEvent(new w.Event('change'));await wait(()=>d.querySelectorAll('.card').length===3);
 click('[data-view="dashboard"]');await wait(()=>d.querySelectorAll('.stat').length===4);
 click('[data-view="paper"]');await wait(()=>d.querySelectorAll('.card').length===6);
 d.querySelector('#query').value='graph';d.querySelector('#search-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>d.querySelectorAll('.card').length===1);
 click('#clear-search');await wait(()=>d.querySelectorAll('.card').length===6);
 d.querySelector('#mode').value='live';d.querySelector('#mode').dispatchEvent(new w.Event('change'));await wait(()=>d.querySelector('.empty'));
 d.querySelector('#query').value='graph';d.querySelector('#search-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait(()=>d.querySelectorAll('.card').length===3);
 // Simulate a delayed mode initialization arriving after a newer selection.
 const realFetch=w.fetch;
 let releaseDemo;
 w.fetch=(path,options)=>path==='/api/v1/demo'?new Promise(resolve=>{releaseDemo=()=>realFetch(path,options).then(resolve)}):realFetch(path,options);
 const pendingDemo=w.setMode('demo');
 await w.setMode('live');
 releaseDemo();await pendingDemo;
 assert.equal(d.querySelector('#mode').value,'live');
 assert.equal(d.querySelector('#demo-banner').hidden,true);
 w.fetch=realFetch;
 // A blocked browser storage setting must not prevent the application from loading.
 Object.defineProperty(w,'localStorage',{configurable:true,get(){throw Error('Storage disabled')}});
 await w.setMode('demo');
 assert.equal(d.querySelector('#mode').value,'demo');
 assert.equal(d.querySelector('#feedback').className,'');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({dom:'jsdom',api:'actual FastAPI via TestClient',demo_cards:6,bookmarks:true,notes:true,deadline_filter:true,search:true,dashboard:true,refresh_polling:true,mode_isolation:true,mode_race:true,blocked_storage:true,errors}));
 dom.window.close();child.stdin.end();
})().catch(e=>{console.error(e);dom.window.close();child.kill();process.exit(1)});
